### ISSUE TITLE
Failed to detect set buildpack https://github.com/dmathieu/heroku-buildpack-submodules

### ISSUE THREAD

**Issue by augnustin** [dmathieu/heroku-buildpack-submodules#1]
I cannot push to heroku anymore:

```
remote: -----> Failed to detect set buildpack https://github.com/dmathieu/heroku-buildpack-submodules
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !   Push rejected to myapp.
remote: 
To https://git.heroku.com/myapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/myapp.git'
```

Any clue what is going on?

**Comment by dmathieu** [comment]
This error means the [bin/detect](https://github.com/dmathieu/heroku-buildpack-submodules/blob/master/bin/detect) script returns a non-zero exit code. It would happen if your app doesn't have a `.gitmodules` file.

**Comment by augnustin** [comment]
Thanks for quick reply!
Indeed, if I `heroku run /bin/bash` there is no `.gitmodules` in there. But it seems like it is heroku removing it, because it is there in my local git and in github. Any idea on why would it be deleted?

**Comment by dmathieu** [comment]
How are you deploying? I'm pretty sure heroku does not remove that file.

**Comment by augnustin** [comment]
I tried both `git push heroku master` or `git push origin master` to compare results.

In both cases, I can't find the `.gitmodules` afterward.

**Comment by dmathieu** [comment]
What is origin?
Also, when using the heroku git server, you don't need this buildpack. Submodules will be installed automatically.
This buildpack is only required if you wish to deploy through the API, or with GitHub Sync.

**Comment by augnustin** [comment]
My bad that's it. If I `git push heroku master`, `.gitmodules` becomes deleted, I guess during the beginning of the deploy process: 

```
remote: Git submodules detected, installing:
remote: Submodule 'app/views/editable' (https://username:password@github.com/myapp/myapp_submodule.git) registered for path 'app/views/editable'
remote: Submodule path 'app/views/editable': checked out 'a8c52f14a5ddd6adee75d427d9b3cc9da67b36b1'
```

Which prevents me from being able to `git push heroku master` straight....

**Comment by dmathieu** [comment]
With b37ffe4361bb9c975dd8e93068c9d296365d748c, your build shouldn't fail anymore.

**Comment by augnustin** [comment]
Great! Thanks!

**Comment by covid-vaccines** [comment]
Hi! I am having a similar problem, as I am new to using heroku (so I'm sorry to bug you with this!!). Part of my project requires data from a Git repo, but when I try to run `git pull origin master` or `git submodule update` I get the `fatal: not a Git repository` error. I am using the heroku Git server, and I have set the submodule with heroku, but when I login to the console, there is no .gitmodules or .git file, so the environment doesn't recognize anything as Git (even though the data comes from a Git server, and it recognizes that my submodule is a repo and clones into it initially). I have tried using this buildpack too but I don't think that's the real issue. Do you know how I am supposed to pull effectively (and automatically) the new data every night? I could setup an external server for the data, but it seems like it doesn't need to be this complicated... thanks so much!!

**Comment by dmathieu** [comment]
My recommendation would be for you to open a support ticket with Heroku.

**Comment by Michaelhess17** [comment]
Thanks so much for taking the time to a answer this. I will do this but for the time being, I will just use `wget` to download the data I need!
