### ISSUE TITLE
Heroku-22 and no system Ruby

### ISSUE THREAD

**Issue by edmorley** [dmathieu/heroku-buildpack-submodules#7]
Hi!

The Heroku-22 stack was just released:
https://devcenter.heroku.com/changelog-items/2429

In Heroku-22, there is no longer a system install of Ruby:
https://devcenter.heroku.com/articles/heroku-22-stack#system-ruby-is-no-longer-installed

This buildpack uses Ruby here:
https://github.com/dmathieu/heroku-buildpack-submodules/blob/b3424d43422a653c7b927d0c975456ec1e3e6e33/bin/install_git_submodules.rb

In order for this buildpack to work on Heroku-22, one of the following will be necessary:
1. Have the buildpack vendor Ruby for use by this script (for an example of a buildpack doing this, see https://github.com/heroku/heroku-buildpack-nginx/pull/103).
2. Convert the buildpack to use shell/bash scripts instead.
3. Have users of this buildpack add the `heroku/ruby` buildpack prior to this one (they will also need to add a minimal `Gemfile` to their app source, if not already present, so the Ruby buildpack passes detection).

**Comment by dmathieu** [comment]
Hey Ed!

Thank you for reporting this.
Would you be interested in taking ownership of this repository, or transferring it to a more heroku-related organization?

I built this buildpack for customers while I was working at heroku, but since I'm not there, haven't used it in years and am not using the Heroku platform at the moment, I don't think I'm the best person to own it anymore.

**Comment by edmorley** [comment]
Hi Damien, hope you are well! :-)

I unfortunately don't have the bandwidth to take ownership of this buildpack personally. I would move it under the `heroku` org, but we no longer have permissions to do that for public repos, and instead have to go through an open source approval process (even for existing public repos), which involves quite a bit of time and red tape 😞 

For reference, there are only ~700 builds for this buildpack in the last 30 days.

I think what I'll do is open a PR to perform option 1 (it will be much quicker/less error prone than option 2).
